version: '2.2'
services:
  ngin:
    image: "${ImageName}:${ImageTag}"
    volumes:
      - ./deploy/nginx.template:/etc/nginx/conf.d/nginx.template:ro
      - nginx-logs:/var/log/nginx
    expose:
      - "80"
    restart: "unless-stopped"
    cpu_count: 1
    mem_limit: 536870912
    networks:
      - default
    environment:
     - NGINX_PORT=${NGINX_PORT}
     - HOST_NAME=${HOST_NAME}
     - API_SERVER=${API_SERVER}
     - API_PORT=${API_PORT}
     - VIRTUAL_HOST=${URL_HOST_NAME}
     - DOLLAR=$$
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    hostname: ${URL_HOST_NAME}
volumes:
  nginx-logs:
networks:
  default:
    external:
      name: sites

