// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // ContactStatuses
    [Table("ContactStatuses", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ContactStatus: Entity
    {
        // ContactStatus

        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 50)

        [Column(@"Sort", Order = 3, TypeName = "int")]
        [Display(Name = "Sort")]
        public int Sort { get; set; } // Sort

        // Reverse navigation

        /// <summary>
        /// Child Contacts where [Contacts].[StatusId] point to this entity (FK_Contacts_ContactStatuses)
        /// </summary>
        public System.Collections.Generic.ICollection<Contact> Contacts { get; set; } // Contacts.FK_Contacts_ContactStatuses

        public ContactStatus()
        {
            Sort = 0;
            Contacts = new System.Collections.Generic.List<Contact>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
