// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // Contracts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ContractConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Contract>
    {
        public ContractConfiguration()
            : this("dbo")
        {
        }

        public ContractConfiguration(string schema)
        {
            Property(x => x.Number).IsOptional().IsUnicode(false);
            Property(x => x.UserId).IsOptional();
            Property(x => x.Version).IsFixedLength();

            HasMany(t => t.ServiceAreas).WithMany(t => t.Contracts).Map(m =>
            {
                m.ToTable("ContractServiceAreas", "dbo");
                m.MapLeftKey("ContractId");
                m.MapRightKey("ServiceAreaId");
            });
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
