// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // Contacts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ContactConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Contact>
    {
        public ContactConfiguration()
            : this("dbo")
        {
        }

        public ContactConfiguration(string schema)
        {
            Property(x => x.FirstName).IsUnicode(false);
            Property(x => x.LastName).IsUnicode(false);
            Property(x => x.Title).IsOptional().IsUnicode(false);
            Property(x => x.Email).IsOptional().IsUnicode(false);
            Property(x => x.AddressId).IsOptional();

            HasMany(t => t.Customers).WithMany(t => t.Contacts).Map(m =>
            {
                m.ToTable("CustomerContacts", "dbo");
                m.MapLeftKey("ContactId");
                m.MapRightKey("CustomerId");
            });
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
