// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // CustomerPhones
    [Table("CustomerPhones", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class CustomerPhone: BaseEntity
    {
        // CustomerPhone
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"CustomerId", Order = 1, TypeName = "int")]
        [Index(@"PK_CustomerPhones", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Customer ID")]
        public int CustomerId { get; set; } // CustomerId (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Phone", Order = 2, TypeName = "varchar")]
        [Index(@"PK_CustomerPhones", 2, IsUnique = true, IsClustered = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Key]
        [Phone]
        [Display(Name = "Phone")]
        public string Phone { get; set; } // Phone (Primary key) (length: 20)

        [Column(@"Extension", Order = 3, TypeName = "varchar")]
        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Extension")]
        public string Extension { get; set; } // Extension (length: 5)

        [Column(@"PhoneTypeId", Order = 4, TypeName = "int")]
        [Display(Name = "Phone type ID")]
        public int PhoneTypeId { get; set; } // PhoneTypeId

        [Column(@"IsPrimary", Order = 5, TypeName = "bit")]
        [Display(Name = "Is primary")]
        public bool IsPrimary { get; set; } // IsPrimary

        // Foreign keys

        /// <summary>
        /// Parent Customer pointed by [CustomerPhones].([CustomerId]) (FK_CustomerPhones_Customers)
        /// </summary>
        [ForeignKey("CustomerId")] public Customer Customer { get; set; } // FK_CustomerPhones_Customers

        /// <summary>
        /// Parent PhoneType pointed by [CustomerPhones].([PhoneTypeId]) (FK_CustomerPhones_PhoneTypes)
        /// </summary>
        [ForeignKey("PhoneTypeId")] public PhoneType PhoneType { get; set; } // FK_CustomerPhones_PhoneTypes

        public CustomerPhone()
        {
            Extension = "";
            IsPrimary = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
