// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // Customers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class CustomerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Customer>
    {
        public CustomerConfiguration()
            : this("dbo")
        {
        }

        public CustomerConfiguration(string schema)
        {
            Property(x => x.Name).IsUnicode(false);
            Property(x => x.Version).IsFixedLength();

            HasMany(t => t.Documents).WithMany(t => t.Customers).Map(m =>
            {
                m.ToTable("CustomerDocuments", "dbo");
                m.MapLeftKey("CustomerId");
                m.MapRightKey("DocumentId");
            });
            HasMany(t => t.Notes).WithMany(t => t.Customers).Map(m =>
            {
                m.ToTable("CustomerNotes", "dbo");
                m.MapLeftKey("CustomerId");
                m.MapRightKey("NoteId");
            });
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
