// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // Documents
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class DocumentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Document>
    {
        public DocumentConfiguration()
            : this("dbo")
        {
        }

        public DocumentConfiguration(string schema)
        {
            Property(x => x.Name).IsUnicode(false);
            Property(x => x.UploadedBy).IsOptional();
            Property(x => x.FilePath).IsUnicode(false);

            HasMany(t => t.Users).WithMany(t => t.Documents).Map(m =>
            {
                m.ToTable("UserDocuments", "dbo");
                m.MapLeftKey("DocumentId");
                m.MapRightKey("UserId");
            });
            HasMany(t => t.Goods).WithMany(t => t.Documents).Map(m =>
            {
                m.ToTable("GoodDocuments", "dbo");
                m.MapLeftKey("DocumentId");
                m.MapRightKey("GoodId");
            });
            HasMany(t => t.CustomerLocations).WithMany(t => t.Documents).Map(m =>
            {
                m.ToTable("CustomerLocationDocuments", "dbo");
                m.MapLeftKey("DocumentId");
                m.MapRightKey("CustomerLocationId");
            });
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
