// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // Documents
    [Table("Documents", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class Document: Entity, IDocument
    {
        // Document

        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 200)

        [Column(@"DateUpload", Order = 3, TypeName = "datetime")]
        [Display(Name = "Date upload")]
        public System.DateTime DateUpload { get; set; } // DateUpload

        [Column(@"UploadedBy", Order = 4, TypeName = "int")]
        [Display(Name = "Uploaded by")]
        public int? UploadedBy { get; set; } // UploadedBy

        [Column(@"FilePath", Order = 5, TypeName = "varchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "File path")]
        public string FilePath { get; set; } // FilePath (length: 200)

        // Reverse navigation

        /// <summary>
        /// Child Customers (Many-to-Many) mapped by table [CustomerDocuments]
        /// </summary>
        public System.Collections.Generic.ICollection<Customer> Customers { get; set; } // Many to many mapping
        /// <summary>
        /// Child CustomerLocations (Many-to-Many) mapped by table [CustomerLocationDocuments]
        /// </summary>
        public System.Collections.Generic.ICollection<CustomerLocation> CustomerLocations { get; set; } // Many to many mapping
        /// <summary>
        /// Child Goods (Many-to-Many) mapped by table [GoodDocuments]
        /// </summary>
        public System.Collections.Generic.ICollection<Good> Goods { get; set; } // Many to many mapping
        /// <summary>
        /// Child Users (Many-to-Many) mapped by table [UserDocuments]
        /// </summary>
        public System.Collections.Generic.ICollection<User> Users { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Documents].([UploadedBy]) (FK_Documents_Users)
        /// </summary>
        [ForeignKey("UploadedBy")] public User User { get; set; } // FK_Documents_Users

        public Document()
        {
            DateUpload = System.DateTime.Now;
            Customers = new System.Collections.Generic.List<Customer>();
            Users = new System.Collections.Generic.List<User>();
            Goods = new System.Collections.Generic.List<Good>();
            CustomerLocations = new System.Collections.Generic.List<CustomerLocation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
