// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    public partial interface IPrimaryContext : System.IDisposable, IContext
    {
        System.Data.Entity.DbSet<Address> Addresses { get; set; } // Addresses
        System.Data.Entity.DbSet<AuthApplicationType> AuthApplicationTypes { get; set; } // AuthApplicationTypes
        System.Data.Entity.DbSet<AuthClient> AuthClients { get; set; } // AuthClients
        System.Data.Entity.DbSet<AuthToken> AuthTokens { get; set; } // AuthTokens
        System.Data.Entity.DbSet<AuthUser> AuthUsers { get; set; } // AuthUsers
        System.Data.Entity.DbSet<ClaimType> ClaimTypes { get; set; } // ClaimTypes
        System.Data.Entity.DbSet<ClaimValue> ClaimValues { get; set; } // ClaimValues
        System.Data.Entity.DbSet<Contact> Contacts { get; set; } // Contacts
        System.Data.Entity.DbSet<ContactPhone> ContactPhones { get; set; } // ContactPhones
        System.Data.Entity.DbSet<ContactStatus> ContactStatus { get; set; } // ContactStatuses
        System.Data.Entity.DbSet<Contract> Contracts { get; set; } // Contracts
        System.Data.Entity.DbSet<ContractStatus> ContractStatus { get; set; } // ContractStatuses
        System.Data.Entity.DbSet<Country> Countries { get; set; } // Countries
        System.Data.Entity.DbSet<Customer> Customers { get; set; } // Customers
        System.Data.Entity.DbSet<CustomerAddress> CustomerAddresses { get; set; } // CustomerAddresses
        System.Data.Entity.DbSet<CustomerLocation> CustomerLocations { get; set; } // CustomerLocations
        System.Data.Entity.DbSet<CustomerLocationAddress> CustomerLocationAddresses { get; set; } // CustomerLocationAddresses
        System.Data.Entity.DbSet<CustomerPhone> CustomerPhones { get; set; } // CustomerPhones
        System.Data.Entity.DbSet<CustomerSource> CustomerSources { get; set; } // CustomerSources
        System.Data.Entity.DbSet<CustomerStatus> CustomerStatus { get; set; } // CustomerStatuses
        System.Data.Entity.DbSet<Document> Documents { get; set; } // Documents
        System.Data.Entity.DbSet<Good> Goods { get; set; } // Goods
        System.Data.Entity.DbSet<Image> Images { get; set; } // Images
        System.Data.Entity.DbSet<LocationService> LocationServices { get; set; } // LocationServices
        System.Data.Entity.DbSet<Note> Notes { get; set; } // Notes
        System.Data.Entity.DbSet<PhoneType> PhoneTypes { get; set; } // PhoneTypes
        System.Data.Entity.DbSet<RefactorLog> RefactorLogs { get; set; } // __RefactorLog
        System.Data.Entity.DbSet<ServiceArea> ServiceAreas { get; set; } // ServiceAreas
        System.Data.Entity.DbSet<ServiceDivision> ServiceDivisions { get; set; } // ServiceDivisions
        System.Data.Entity.DbSet<ServiceType> ServiceTypes { get; set; } // ServiceTypes
        System.Data.Entity.DbSet<Setting> Settings { get; set; } // Settings
        System.Data.Entity.DbSet<State> States { get; set; } // States
        System.Data.Entity.DbSet<SubcontractorStatus> SubcontractorStatus { get; set; } // SubcontractorStatuses
        System.Data.Entity.DbSet<UnitType> UnitTypes { get; set; } // UnitTypes
        System.Data.Entity.DbSet<User> Users { get; set; } // Users
        System.Data.Entity.DbSet<UserPhone> UserPhones { get; set; } // UserPhones
        System.Data.Entity.DbSet<UserRole> UserRoles { get; set; } // UserRoles
        System.Data.Entity.DbSet<UserRoleClaim> UserRoleClaims { get; set; } // UserRoleClaims
        System.Data.Entity.DbSet<WorkOrderStatus> WorkOrderStatus { get; set; } // WorkOrderStatuses

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
