// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // LocationServices
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class LocationServiceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LocationService>
    {
        public LocationServiceConfiguration()
            : this("dbo")
        {
        }

        public LocationServiceConfiguration(string schema)
        {
            Property(x => x.Price).HasPrecision(19,4);
            Property(x => x.Version).IsFixedLength();
            Property(x => x.ShortDescription).IsUnicode(false);
            Property(x => x.LongDescription).IsUnicode(false);

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
