// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // Notes
    [Table("Notes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class Note: Entity
    {
        // Note

        [Column(@"Title", Order = 2, TypeName = "varchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Title")]
        public string Title { get; set; } // Title (length: 100)

        [Column(@"NoteText", Order = 3, TypeName = "varchar")]
        [MaxLength(5000)]
        [StringLength(5000)]
        [Display(Name = "Note text")]
        public string NoteText { get; set; } // NoteText (length: 5000)

        // Reverse navigation

        /// <summary>
        /// Child Customers (Many-to-Many) mapped by table [CustomerNotes]
        /// </summary>
        public System.Collections.Generic.ICollection<Customer> Customers { get; set; } // Many to many mapping

        public Note()
        {
            Title = "";
            NoteText = "";
            Customers = new System.Collections.Generic.List<Customer>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
