// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // States
    [Table("States", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class State: Entity
    {
        // State

        [Column(@"StateCode", Order = 2, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "State code")]
        public string StateCode { get; set; } // StateCode (length: 2)

        [Column(@"Name", Order = 3, TypeName = "varchar")]
        [MaxLength(64)]
        [StringLength(64)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 64)

        [Column(@"TaxRate", Order = 4, TypeName = "decimal")]
        [Display(Name = "Tax rate")]
        public decimal? TaxRate { get; set; } // TaxRate

        // Reverse navigation

        /// <summary>
        /// Child Addresses where [Addresses].[StateId] point to this entity (FK_Addresses_States)
        /// </summary>
        public System.Collections.Generic.ICollection<Address> Addresses { get; set; } // Addresses.FK_Addresses_States

        public State()
        {
            Addresses = new System.Collections.Generic.List<Address>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
