// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using TrackerEnabledDbContext;

    // UserPhones
    [Table("UserPhones", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class UserPhone: BaseEntity
    {
        // UserPhone
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"UserId", Order = 1, TypeName = "int")]
        [Index(@"PK_UserPhones", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "User ID")]
        public int UserId { get; set; } // UserId (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Phone", Order = 2, TypeName = "varchar")]
        [Index(@"PK_UserPhones", 2, IsUnique = true, IsClustered = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Key]
        [Phone]
        [Display(Name = "Phone")]
        public string Phone { get; set; } // Phone (Primary key) (length: 20)

        [Column(@"Extension", Order = 3, TypeName = "varchar")]
        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Extension")]
        public string Extension { get; set; } // Extension (length: 5)

        [Column(@"PhoneTypeId", Order = 4, TypeName = "int")]
        [Display(Name = "Phone type ID")]
        public int PhoneTypeId { get; set; } // PhoneTypeId

        [Column(@"IsPrimary", Order = 5, TypeName = "bit")]
        [Display(Name = "Is primary")]
        public bool IsPrimary { get; set; } // IsPrimary

        // Foreign keys

        /// <summary>
        /// Parent PhoneType pointed by [UserPhones].([PhoneTypeId]) (FK_UserPhones_PhoneTypes)
        /// </summary>
        [ForeignKey("PhoneTypeId")] public PhoneType PhoneType { get; set; } // FK_UserPhones_PhoneTypes

        /// <summary>
        /// Parent User pointed by [UserPhones].([UserId]) (FK_UserPhones_Users)
        /// </summary>
        [ForeignKey("UserId")] public User User { get; set; } // FK_UserPhones_Users

        public UserPhone()
        {
            Extension = "";
            IsPrimary = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
